### ISSUE TITLE
Setup HVaR and Yeild Curve

### ISSUE THREAD

**Issue by nssales** [OpenGamma/OpenSIMM#3]
Hello,

We need help to setup HVaR in OpenGamma. So I will really appreciate if you can please give us the following information.
1) How to setup HVaR. Do we use portfolio Mapping using "Scheduled Method"
2) How to configure Yield Curve and where can we see the Zero Rates
3) What are the Default Parameters and Values that are used in HVaR.
4) Is there a way to output the Cash Flow of Trade or Portfolio.
5) Can we FIX the Asof Date and it always changes to the System Date.
6) Can you help us to run the engine-debugger.bat

Thank you,

**Comment by jonathansenior** [comment]
Thanks for your query. This is being handled through our support desk so I will close the issue here.

**Comment by nssales** [comment]
Hello Jonathan.....Can you please let us know if this issue is being forwarded to Support Desk OR Do I have to contact them separately.

**Comment by jonathansenior** [comment]
Hi. This has been logged in our support desk for you.

**Comment by nssales** [comment]
Thank you
